---
- name: Get raspa code code from github
  git:
    repo: "{{ raspa_url }}"
    version: "{{ raspa_version }}"
    dest: "{{ raspa_topdir }}"

- name: "Put a line in ~/.profile for RASPA_DIR"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    line: "export RASPA_DIR={{ raspa_install_dir }}"

- name: "Create raspa install dir"
  file:
    path: "{{ raspa_install_dir }}"
    state: directory

- name: install packages
  become: true
  become_user: "{{ root_user }}"
  apt:
    name:
      - autoconf
      - libgmp3-dev
      - gcc
    state: present

- name: raspa - autoreconf
  shell: |
    rm -rf autom4te.cache
    mkdir m4
    aclocal
    autoreconf -i
    automake --add-missing
    autoconf
  args:
    chdir: "{{ raspa_topdir }}"
    creates: "{{ raspa_topdir }}/configure"
  register: raspa_autoreconf
  tags:
    - skip_ansible_lint

# ansiblelint disable rule:ansible0016

- name: raspa - configure
  command: ./configure --prefix={{ raspa_install_dir }}
  args:
    chdir: "{{ raspa_topdir }}"
    creates: "{{ raspa_topdir }}/Makefile"
  register: raspa_configure
  when: raspa_autoreconf.changed
  tags:
    - skip_ansible_lint

- name: raspa - make
  make:
    chdir: "{{ raspa_topdir }}"
  register: raspa_make

# - name: raspa tests
#   import_tasks: tests.yml
#   when: raspa_make.changed and run_tests is defined and run_tests

- name: raspa - make install
  make:
    chdir: "{{ raspa_topdir }}"
    target: install
  when: raspa_make.changed
  register: raspa_make_install
  tags:
    - skip_ansible_lint

- name: "Put a line in ~/.profile to add raspa binary to the path"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    line: "export PATH=${PATH}:{{ raspa_install_dir }}"

- include_role:
    name: release_notes
  vars:
    section: "raspa"
    option: "version"
    value: "{{ raspa_version }}"
  when: release_notes is defined and release_notes


- include_role:
    name: release_notes
  vars:
    section: "raspa"
    option: "usage"
    value: >-
        raspa is installed in {{ raspa_topdir }}.
        'simulate' has been added to the PATH
  when: release_notes is defined and release_notes
